### ISSUE TITLE
Requesting Enhancement: Summary files ala FastQC

### ISSUE THREAD

**Issue by harish0201** [fxwiegand/fastqc-rs#1]
Hey!

Thanks for the tool! It is blindingly fast and real easy to use.

One thing that I have a request for is to generate a summary file(s) similar to FastQC so that the same can be parsed with MultiQC to summarize over the entire datasets.

Would you think that this would be possible?

**Comment by fxwiegand** [comment]
Hello,

thanks for using the tool and for your input! Generating summary files like fastQC sounds doable to me and seems like a great addition. I will take a deeper look into in those summary files when i find time in the next few days.

**Comment by fxwiegand** [comment]
I added a new parameter `-s` for generating a summary file for [MultiQC](https://multiqc.info). There is definitely some room for improvement but should at least work for trying it out and some testing.

@harish0201 let me know what you think and also if you find any problems.
